selection:
	g++ -o bin selection_sort.cpp

insertion:
	g++ -o bin insertion_sort.cpp

bubble:
	g++ -o bin bubble_sort.cpp

count:
	g++ -o bin count_sort.cpp

run:
	./bin

rand:
	g++ -o rand Gera_RAND.cpp

num:
	gcc -o num gera_num.c